#!/usr/bin/perl

$_ = join('',<>);
s/\\\R//msg;
for $_ (split /\R/) {
   if (/(^\s*[^#]+?): (.+)$/) {
      ($var,$msg) = ($1, $2);
      $c = ($msg =~ s/%s/~s/g );
      $_ = "$var: ___$msg"."___";
      while ($c) { $_ .= "%s"; $c--; }
   }
   print;
   print "\n";
}
