#!/usr/bin/perl
use lib '/Users/arenger/perl5/lib/perl5';
use strict;
use warnings;
use DBI;
$| = 1;

our $dbc = DBI->connect( 'DBI:mysql:hilas', 'hilas', 'hilas')
   or die "Could not connect to database: $DBI::errstr";

my $sel = $dbc->prepare(
   "select lintsig, domainid, wot0 from analysis");

open(C,'>','xref.dat');
open(T,'>','test.dat');
$sel->execute();
while (my @row = $sel->fetchrow_array) {
   my @ids = split(/,/, shift @row);
   #if (!@ids && (@ids > 10)) { next; }
   if (!@ids) { next; }
   printf T ("+1 %s:1\n", join(':1 ', @ids));
   print  C join(',', $row[0], defined($row[1]) ? $row[1] : -1)."\n";
}
close(C);
close(T);

$dbc->disconnect();
