#!/usr/bin/perl
use lib '/Users/arenger/perl5/lib/perl5';
use strict;
use warnings;
use DBI;
$| = 1;

if (@ARGV != 5) {
   print "usage: $0 z G_lo G_hi B_lo B_hi\n";
   exit;
}
my($z,$Glo,$Ghi,$Blo,$Bhi) = @ARGV;

our $dbc = DBI->connect( 'DBI:mysql:hilas', 'hilas', 'hilas')
   or die "Could not connect to database: $DBI::errstr";

my $sel = $dbc->prepare(
   "select lintsig from analysis ".
   "where wot0 between ? and ?");
   #"where wot0 between ? and ? and htmlbytes > 511");

open(T,'>','train.dat');
$sel->execute($Glo, $Ghi);
while (my @row = $sel->fetchrow_array) {
   my @ids = split(/,/, $row[0]);
   if (!@ids || (@ids > $z)) { next; }
   #if (!@ids) { next; }
   printf T ("+1 %s:1\n", join(':1 ', @ids));
}

$sel->execute($Blo, $Bhi);
while (my @row = $sel->fetchrow_array) {
   my @ids = split(/,/, $row[0]);
   if (!@ids || (@ids > $z)) { next; }
   #if (!@ids) { next; }
   printf T ("-1 %s:1\n", join(':1 ', @ids));
}
close(T);

$dbc->disconnect();
